backend:
  name: github
  repo: KallendJack/fem-gatsby-introduction

media_folder: static/assets
public_folder: /assets

collections:
  - name: page
    label: Page
    folder: markdown-pages
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: title, label: Title }
      - { name: description, label: Description }
